stages:
  - name: Build
    steps:
      - runScriptConfig:
          image: link-cloud/composer:latest
          shellScript: |-
            composer install
  - name: Publish
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: example-php:${CICD_EXECUTION_SEQUENCE}
  - name: Deploy
    steps:
      - applyYamlConfig:
          path: ./deployment.yaml
